name: C++ Automated Test (Makefile)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. 外部ライブラリのインストール
      - name: Install Official Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libopencv-dev
          sudo apt-get install -y libssl-dev libssh-dev

      # 2. 自作 .deb パッケージのインストール
      - name: Install Custom DEB Package
        run: |
          sudo apt-get install -y ./packages/fmt9.1.0_ubuntu2004_amd64.deb
          sudo apt-get install -y ./packages/SimpleGtk1.0.10_ubuntu2204_amd64.deb

      # 3. テストのビルドと実行（Makefileにお任せ）
      - name: Run Tests
        run: make test